Projet_E_Commerce-master/symfony/src/AppBundle/Entity/orders.php
<?php

namespace AppBundle\Entity;

/**
 * orders
 */
class orders
{
    /**
     * @var int
     */
    private $id_order;

    /**
     * @var int
     */
    private $idUser;

    /**
     * @var int
     */
    private $orderStatus;

    /**
     * @var float
     */
    private $totalTTC;

    /**
     * @var float
     */
    private $totalHT;

    /**
     * @var int
     */
    private $nbProduct;

    /**
     * @var float
     */
    private $totalWeight;

    /**
     * @var \DateTime
     */
    private $dateOrder;

    /**
     * @var int
     */
    private $idAdress;

    private $adresses;

    private $user;

    private $basketId;

    private $basketes;

    public function setBasketes($basket){
        $this->basketes = $basket;
    }

    public function setUser($user){
        $this->user = $user;
    }

    public function setAdresses($adress){
        $this->adresses = $adress;
    }

    public function getBasketes(){
        return $this->basketes;
    }

    public function getBasketId(){
        return $this->basketId;
    }

    public function getUser(){
        return $this->user;
    }

    public function getAdresses(){
        return $this->adresses;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getIdOrder()
    {
        return $this->id_order;
    }

    /**
     * Set idUser
     *
     * @param integer $idUser
     *
     * @return orders
     */
    public function setIdUser($idUser)
    {
        $this->idUser = $idUser;

        return $this;
    }

    /**
     * Get idUser
     *
     * @return int
     */
    public function getIdUser()
    {
        return $this->idUser;
    }

    /**
     * Set orderStatus
     *
     * @param integer $orderStatus
     *
     * @return orders
     */
    public function setOrderStatus($orderStatus)
    {
        $this->orderStatus = $orderStatus;

        return $this;
    }

    /**
     * Get orderStatus
     *
     * @return int
     */
    public function getOrderStatus()
    {
        return $this->orderStatus;
    }

    /**
     * Set totalTTC
     *
     * @param float $totalTTC
     *
     * @return orders
     */
    public function setTotalTTC($totalTTC)
    {
        $this->totalTTC = $totalTTC;

        return $this;
    }

    /**
     * Get totalTTC
     *
     * @return float
     */
    public function getTotalTTC()
    {
        return $this->totalTTC;
    }

    /**
     * Set totalHT
     *
     * @param float $totalHT
     *
     * @return orders
     */
    public function setTotalHT($totalHT)
    {
        $this->totalHT = $totalHT;

        return $this;
    }

    /**
     * Get totalHT
     *
     * @return float
     */
    public function getTotalHT()
    {
        return $this->totalHT;
    }

    /**
     * Set nbProduct
     *
     * @param integer $nbProduct
     *
     * @return orders
     */
    public function setNbProduct($nbProduct)
    {
        $this->nbProduct = $nbProduct;

        return $this;
    }

    /**
     * Get nbProduct
     *
     * @return int
     */
    public function getNbProduct()
    {
        return $this->nbProduct;
    }

    /**
     * Set totalWeight
     *
     * @param float $totalWeight
     *
     * @return orders
     */
    public function setTotalWeight($totalWeight)
    {
        $this->totalWeight = $totalWeight;

        return $this;
    }

    /**
     * Get totalWeight
     *
     * @return float
     */
    public function getTotalWeight()
    {
        return $this->totalWeight;
    }

    /**
     * Set dateOrder
     *
     * @param \DateTime $dateOrder
     *
     * @return orders
     */
    public function setDateOrder($dateOrder)
    {
        $this->dateOrder = $dateOrder;

        return $this;
    }

    /**
     * Get dateOrder
     *
     * @return \DateTime
     */
    public function getDateOrder()
    {
        return $this->dateOrder;
    }

    /**
     * Set idAdress
     *
     * @param integer $idAdress
     *
     * @return orders
     */
    public function setIdAdress($idAdress)
    {
        $this->idAdress = $idAdress;

        return $this;
    }

    /**
     * Get idAdress
     *
     * @return int
     */
    public function getIdAdress()
    {
        return $this->idAdress;
    }
}

Projet_E_Commerce-master/symfony/src/AppBundle/Controller/AdminUsersController.php
<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;


class AdminUsersController extends Controller
{
    /**
     * @Route("/admin/users_list")
     */
    public function listUsersAction(Request $request)
    {
        $db = $this->getDoctrine()->getManager();
        $users = $db->getRepository('AppBundle:users')->findAll();

        /**
         * @var $paginator\Knp\Component\Pager\Paginator
         */
        $paginator = $this->get('knp_paginator');
        $result = $paginator->paginate(
            $users,
            $request->query->getInt('page', 1),
            $request->query->getInt('limit', 5)
        );


        return $this->render('AppBundle:AdminUsers:list_users.html.twig', array(
            'users' => $result,
        ));
    }

    /**
     * @Route("/admin/user/{id}")
     */
    public  function userAction($id)
    {
        $db = $this->getDoctrine()->getManager();
        $user = $db->getRepository('AppBundle:users')->find($id);
        $orders = $db->getRepository('AppBundle:orders')->findByIdUser($id);
        $adress = $db->getRepository('AppBundle:adress')->findByUser($id);

        return $this->render('AppBundle:AdminUsers:user_info.html.twig', array(
            'user' => $user,
            'orders' => $orders,
            'adresses' => $adress,
        ));
    }

}

Projet_E_Commerce-master/symfony/src/AppBundle/Resources/views/AdminUsers/list_users.html.twig
{% extends "::baseAdmin.html.twig" %}

{% block title %}AppBundle:AdminUsers:listUsers{% endblock %}

{% block body %}
<h1>Welcome to the AdminUsers:listUsers page</h1>
    <div class="col-lg-6 mb-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title mb-4">Hoverable Table</h5>
                <table class="table table-hover">
                    <thead>
                    <tr class="">
                        <th>#</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Roles</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                    <tr>
                        <th scope="row">{{ user.id }}</th>
                        <td><a href="/admin/user/{{ user.id }}"><strong>{{ user.firstName }}</strong></a></td>
                        <td>{{ user.name }}</td>
                        <td>{{ user.email }}</td>
                        {% for role in user.roles %}
                        <td>{{ role }}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="navigation">
        {{ knp_pagination_render(users) }}
    </div>
{% endblock %}

Projet_E_Commerce-master/symfony/src/AppBundle/Resources/views/AdminUsers/user_info.html.twig
{% extends "::baseAdmin.html.twig" %}

{% block title %}AppBundle:AdminUsers:Infos Users{% endblock %}

{% block body %}
    <div class="row">
        <h2>{{ user.name }} {{ user.firstname }}</h2>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h3>Commandes Passées</h3>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table center-aligned-table">
            <thead>
            <tr class="text-primary">
                <th>No</th>
                <th>No Products</th>
                <th>Total Weight</th>
                <th>Created</th>
                <th>Status</th>
                <th>Adress</th>
                <th>Price</th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for order in orders %}
                <tr class="">
                <td>{{ order.idOrder }}</td>
                <td>{{ order.nbProduct }}</td>
                <td>{{ order.totalWeight }}</td>
                <td>{{ order.dateOrder|date('d-m-Y') }}</td>
                {% if order.orderStatus == 0 %}
                <td><label class="btn btn-warning btn-sm">Waiting</label></td>
                    {% elseif order.orderStatus == 1 %}
                        <td><label class="btn btn-primary btn-sm">in Progress</label></td>
                    {% elseif order.orderStatus == 2 %}
                        <td><label class="btn btn-info btn-sm">in Delivery</label></td>
                        {% elseif order.orderStatus == 3 %}
                            <td><label class="btn btn-success btn-sm">Finish</label></td>
                {% else  %}
                    <td><label class="btn btn-danger btn-sm">Cancel</label></td>
                {% endif %}
                <td>{{ order.adresses.nameAdress }}</td>
                <td>{{ order.totalTTC }}€</td>
                <td><a href="/admin/manage_order/{{ order.idOrder }}" class="btn btn-primary btn-md">Manage</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h3>Les Adresses</h3>
        </div>
    </div>
    <div class="row">
        {% for adress in adresses %}
            <div class="adress">
                <p><u>Nom Adresse</u>  :  <strong>{{ adress.nameAdress }}</strong></p>
                <p>{{ adress.nameDesti }}<br>
                    {{ adress.adress }}<br>
                    {{ adress.cp }} {{ adress.city }}<br>
                    {{ adress.country }}
                </p>
            </div>
        {% endfor %}
    </div>
{% endblock %}