Projet_E_Commerce-master/symfony/src/AppBundle/Entity/adress.php
<?php

namespace AppBundle\Entity;

/**
 * adress
 */
class adress
{
    /**
     * @var int
     */
    private $id_adress;

    /**
     * @var string
     */
    private $nameAdress;

    /**
     * @var string
     */
    private $nameDesti;

    /**
     * @var string
     */
    private $adress;

    /**
     * @var int
     */
    private $cp;

    /**
     * @var string
     */
    private $city;

    /**
     * @var string
     */
    private $country;

    /**
     * @var \DateTime
     */
    private $dateCreate;
    /**
     * @var int
     */
    private $visible;

    private $Orders;

    public function getOrders(){
        return $this->Orders;
    }

    public function getVisible(){
        return $this->visible;
    }
    public function setVisible($int){
        $this->visible = $int;
    }

    private $user;


    public function __construct()
    {
        $this->setDateCreate(new \DateTime('NOW'));
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getIdAdress()
    {
        return $this->id_adress;
    }

    /**
     * Get user
     *
     */
    public function getUser()
    {
        return $this->user;
    }

    public function setUser($user){
        $this->user = $user;
    }
    /**
     * Set nameAdress
     *
     * @param string $nameAdress
     *
     * @return adress
     */
    public function setNameAdress($nameAdress)
    {
        $this->nameAdress = $nameAdress;

        return $this;
    }

    /**
     * Get nameAdress
     *
     * @return string
     */
    public function getNameAdress()
    {
        return $this->nameAdress;
    }

    /**
     * Set nameDesti
     *
     * @param string $nameDesti
     *
     * @return adress
     */
    public function setNameDesti($nameDesti)
    {
        $this->nameDesti = $nameDesti;

        return $this;
    }

    /**
     * Get nameDesti
     *
     * @return string
     */
    public function getNameDesti()
    {
        return $this->nameDesti;
    }

    /**
     * Set adress
     *
     * @param string $adress
     *
     * @return adress
     */
    public function setAdress($adress)
    {
        $this->adress = $adress;

        return $this;
    }

    /**
     * Get adress
     *
     * @return string
     */
    public function getAdress()
    {
        return $this->adress;
    }

    /**
     * Set cp
     *
     * @param integer $cp
     *
     * @return adress
     */
    public function setCp($cp)
    {
        $this->cp = $cp;

        return $this;
    }

    /**
     * Get cp
     *
     * @return int
     */
    public function getCp()
    {
        return $this->cp;
    }

    /**
     * Set city
     *
     * @param string $city
     *
     * @return adress
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Set country
     *
     * @param string $country
     *
     * @return adress
     */
    public function setCountry($country)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Get country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Set dateCreate
     *
     * @param \DateTime $dateCreate
     *
     * @return adress
     */
    public function setDateCreate($dateCreate)
    {
        $this->dateCreate = $dateCreate;

        return $this;
    }

    /**
     * Get dateCreate
     *
     * @return \DateTime
     */
    public function getDateCreate()
    {
        return $this->dateCreate;
    }
}

Projet_E_Commerce-master/symfony/src/AppBundle/Entity/basket.php
<?php

namespace AppBundle\Entity;

/**
 * basket
 */
class basket
{
    /**
     * @var int
     */
    private $id_basket;

    /**
     * @var int
     */
    private $userId;

    /**
     * @var int
     */
    private $productNumbers;

    /**
     * @var float
     */
    private $totalHT;

    /**
     * @var float
     */
    private $totalTTC;

    /**
     * @var float
     */
    private $totalWeight;

    /**
     * @var int
     */
    private $statusBasket;

    private $user;

    private $quantities;

    private $Orders;

    public function getOrders(){
        $this->Orders;
    }

    public  function setUser($user){
        $this->user = $user;
    }
    public function getUser(){
        return $this->user;
    }
    public function setQuantities($prod){
        $this->quantities = $prod;
    }
    public function getQuantities(){
        return $this->quantities;
    }
    /**
     * Get id
     *
     * @return int
     */
    public function getIdBasket()
    {
        return $this->id_basket;
    }

    /**
     * Set idUser
     *
     * @param integer $idUser
     *
     * @return basket
     */
    public function setUserId($idUser)
    {
        $this->userId = $idUser;

        return $this;
    }

    /**
     * Get idUser
     *
     * @return int
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Set productNumbers
     *
     * @param integer $productNumbers
     *
     * @return basket
     */
    public function setProductNumbers($productNumbers)
    {
        $this->productNumbers = $productNumbers;

        return $this;
    }

    /**
     * Get productNumbers
     *
     * @return int
     */
    public function getProductNumbers()
    {
        return $this->productNumbers;
    }

    /**
     * Set totalHT
     *
     * @param float $totalHT
     *
     * @return basket
     */
    public function setTotalHT($totalHT)
    {
        $this->totalHT = $totalHT;

        return $this;
    }

    /**
     * Get totalHT
     *
     * @return float
     */
    public function getTotalHT()
    {
        return $this->totalHT;
    }

    /**
     * Set totalTTC
     *
     * @param float $totalTTC
     *
     * @return basket
     */
    public function setTotalTTC($totalTTC)
    {
        $this->totalTTC = $totalTTC;

        return $this;
    }

    /**
     * Get totalTTC
     *
     * @return float
     */
    public function getTotalTTC()
    {
        return $this->totalTTC;
    }

    /**
     * Set totalWeight
     *
     * @param float $totalWeight
     *
     * @return basket
     */
    public function setTotalWeight($totalWeight)
    {
        $this->totalWeight = $totalWeight;

        return $this;
    }

    /**
     * Get totalWeight
     *
     * @return float
     */
    public function getTotalWeight()
    {
        return $this->totalWeight;
    }

    /**
     * Set statusBasket
     *
     * @param integer $statusBasket
     *
     * @return basket
     */
    public function setStatusBasket($statusBasket)
    {
        $this->statusBasket = $statusBasket;

        return $this;
    }

    /**
     * Get statusBasket
     *
     * @return int
     */
    public function getStatusBasket()
    {
        return $this->statusBasket;
    }
}

Projet_E_Commerce-master/symfony/src/AppBundle/Entity/card.php
<?php

namespace AppBundle\Entity;

/**
 * card
 */
class card
{
    /**
     * @var int
     */
    private $id_card;

    /**
     * @var int
     */
    private $idUser;

    /**
     * @var string
     */
    private $numberCard;

    /**
     * @var string
     */
    private $nameUserCard;

    /**
     * @var string
     */
    private $dateExpir;

    /**
     * Get id
     *
     * @return int
     */
    public function getIdCard()
    {
        return $this->id_card;
    }
    private $user;

    public function setUser($user){
        $this->user = $user;
    }

    /**
     * Set idUser
     *
     * @param integer $idUser
     *
     * @return card
     */
    public function setIdUser($idUser)
    {
        $this->idUser = $idUser;

        return $this;
    }

    /**
     * Get idUser
     *
     * @return int
     */
    public function getIdUser()
    {
        return $this->idUser;
    }

    /**
     * Set numberCard
     *
     * @param string $numberCard
     *
     * @return card
     */
    public function setNumberCard($numberCard)
    {
        $this->numberCard = $numberCard;

        return $this;
    }

    /**
     * Get numberCard
     *
     * @return string
     */
    public function getNumberCard()
    {
        return $this->numberCard;
    }

    /**
     * Set nameUserCard
     *
     * @param string $nameUserCard
     *
     * @return card
     */
    public function setNameUserCard($nameUserCard)
    {
        $this->nameUserCard = $nameUserCard;

        return $this;
    }

    /**
     * Get nameUserCard
     *
     * @return string
     */
    public function getNameUserCard()
    {
        return $this->nameUserCard;
    }

    /**
     * Set dateExpir
     *
     * @param string $dateExpir
     *
     * @return card
     */
    public function setDateExpir($dateExpir)
    {
        $this->dateExpir = $dateExpir;

        return $this;
    }

    /**
     * Get dateExpir
     *
     * @return string
     */
    public function getDateExpir()
    {
        return $this->dateExpir;
    }
}

Projet_E_Commerce-master/symfony/src/AppBundle/Entity/products.php
<?php



namespace AppBundle\Entity;



/**

 * products

 */

class products

{

    /**

     * @var int

     */

    private $id_product;



    /**

     * @var string

     */

    private $name;



    /**

     * @var string

     */

    private $ref;



    /**

     * @var string

     */

    private $describ;



    /**

     * @var string

     */

    private $feature;



    /**

     * @var string

     */

    private $color;



    /**

     * @var float

     */

    private $weigth;



    /**

     * @var \DateTime

     */

    private $dateCreate;



    /**

     * @var \DateTime

     */

    private $dateModif;



    /**

     * @var float

     */

    private $priceHT;



    /**

     * @var float

     */

    private $priceTTC;



    /**

     * @var int

     */

    private $statutProduct;


    private $quantities;

    private $categories;

    public  function getQuantities(){
        return $this->quantities;
    }
   /* public function getBasketes(){
        return $this->basketes;
    }*/


    public function getCategories()

    {

        return $this->categories;

    }





    /**

     * Get id

     *

     * @return int

     */

    public function getIdProduct()

    {

        return $this->id_product;

    }

    public function getid_product()
    {
      return $this->id_product;

    }


    /**

     * Set name

     *

     * @param string $name

     *

     * @return products

     */

    public function setName($name)

    {

        $this->name = $name;



        return $this;

    }



    /**

     * Get name

     *

     * @return string

     */

    public function getName()

    {

        return $this->name;

    }



    /**

     * Set ref

     *

     * @param string $ref

     *

     * @return products

     */

    public function setRef($ref)

    {

        $this->ref = $ref;



        return $this;

    }



    /**

     * Get ref

     *

     * @return string

     */

    public function getRef()

    {

        return $this->ref;

    }



    /**

     * Set describ

     *

     * @param string $describ

     *

     * @return products

     */

    public function setDescrib($describ)

    {

        $this->describ = $describ;



        return $this;

    }



    /**

     * Get describ

     *

     * @return string

     */

    public function getDescrib()

    {

        return $this->describ;

    }



    /**

     * Set feature

     *

     * @param string $feature

     *

     * @return products

     */

    public function setFeature($feature)

    {

        $this->feature = $feature;



        return $this;

    }



    /**

     * Get feature

     *

     * @return string

     */

    public function getFeature()

    {

        return $this->feature;

    }



    /**

     * Set color

     *

     * @param string $color

     *

     * @return products

     */

    public function setColor($color)

    {

        $this->color = $color;



        return $this;

    }



    /**

     * Get color

     *

     * @return string

     */

    public function getColor()

    {

        return $this->color;

    }



    /**

     * Set poid

     *

     * @param integer $poid

     *

     * @return products

     */

    public function setWeigth($poid)

    {

        $this->weigth = $poid;



        return $this;

    }



    /**

     * Get poid

     *

     * @return int

     */

    public function getWeigth()

    {

        return $this->weigth;

    }



    /**

     * Set dateCreate

     *

     * @param \DateTime $dateCreate

     *

     * @return products

     */

    public function setDateCreate($dateCreate)

    {

        $this->dateCreate = $dateCreate;



        return $this;

    }



    /**

     * Get dateCreate

     *

     * @return \DateTime

     */

    public function getDateCreate()

    {

        return $this->dateCreate;

    }



    /**

     * Set dateModif

     *

     * @param \DateTime $dateModif

     *

     * @return products

     */

    public function setDateModif($dateModif)

    {

        $this->dateModif = $dateModif;



        return $this;

    }



    /**

     * Get dateModif

     *

     * @return \DateTime

     */

    public function getDateModif()

    {

        return $this->dateModif;

    }



    /**

     * Set priceHT

     *

     * @param float $priceHT

     *

     * @return products

     */

    public function setPriceHT($priceHT)

    {

        $this->priceHT = $priceHT;



        return $this;

    }



    /**

     * Get priceHT

     *

     * @return float

     */

    public function getPriceHT()

    {

        return $this->priceHT;

    }



    /**

     * Set priceTTC

     *

     * @param float $priceTTC

     *

     * @return products

     */

    public function setPriceTTC($priceTTC)

    {

        $this->priceTTC = $priceTTC;



        return $this;

    }



    /**

     * Get priceTTC

     *

     * @return float

     */

    public function getPriceTTC()

    {

        return $this->priceTTC;

    }



    /**

     * Set statutProduit

     *

     * @param integer $statutProduct

     *

     * @return products

     */

    public function setStatutProduct($statutProduit)

    {

        $this->statutProduct= $statutProduit;



        return $this;

    }



    /**

     * Get statutProduct

     *

     * @return int

     */

    public function getStatutProduct()

    {

        return $this->statutProduct;

    }

}

Projet_E_Commerce-master/symfony/src/AppBundle/Resources/views/basket/add_basket.html.twig
{% extends "::base.html.twig" %}

{% block title %}AppBundle:basket:addBasket{% endblock %}

{% block body %}
<form method="post" action="/addBasket/1">
    <label>Quantiter : </label><input type="number" min="0" value="1" name="quantity">
    <input type="submit" value="Ajouter au pannier">
</form>
{% endblock %}

Projet_E_Commerce-master/symfony/src/AppBundle/Resources/views/basket/clear_basket.html.twig
{% extends "::base.html.twig" %}

{% block title %}AppBundle:basket:clearBasket{% endblock %}

{% block body %}
<h1>Welcome to the basket:clearBasket page</h1>
{% endblock %}

Projet_E_Commerce-master/symfony/src/AppBundle/Resources/views/basket/end_basket.html.twig
{% extends "::base.html.twig" %}

{% block title %}Finalisation du pannier{% endblock %}

{% block body %}
    <div class="container">
        {% if app.request.hasPreviousSession %}
            {% for type, messages in app.session.flashbag.all() %}
                {% for message in messages %}
                    <div class="flash-{{ type }}">
                        <div class="alert alert-info alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ message|raw }}
                        </div>

                    </div>
                {% endfor %}
            {% endfor %}
        {% endif %}
        <form action="newCommande" method="post">
            <div class="row">
                <h3><u>Séléctionnez/ajoutez une adresse de livraison</u> : </h3>
            </div>
            <div class="add_adress">
                <strong><a href="/adress/new">Ajouter une adresse postal</a></strong>
            </div>
            {%  for adresse in user.adresses %}
                {% if adresse.visible == 1 %}
                    <div style="display: flex">
                        <input type="radio" name="adress" checked="checked" value="{{ adresse.idAdress }}">
                        <div class="adress">
                            {{ adresse.NameAdress }}
                            {{ adresse.NameDesti }} <br>{{ adresse.adress }} <br>{{ adresse.cp }} {{ adresse.city }}, {{ adresse.country }}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            <div class="row">
                <h3><u>Séléctionnez/ajoutez une carte de paiement</u> :</h3>
            </div>
            <div class="add_card">
                <strong><a href="/newCard">Ajouter une carte de paiement</a></strong>
            </div>
            {%  for card in user.cards %}
                <!--<input type="radio" name="card" selected value="{{ card.idCard }}">Date exipration : {{ card.dateExpir }}-->
            {% endfor %}
            <div class="payer row">
                <button class="btn btn-info btn-md" type="submit">Payer</button>
            </div>
        </form>
    </div>

{% endblock %}

Projet_E_Commerce-master/symfony/src/AppBundle/Resources/views/basket/index.html.twig
{% extends "::base.html.twig" %}


{% block title %}Panier{% endblock %}

{% block body %}
    {% for basket in user.basketes %}
        {% if basket.statusBasket == 1  %}
            <form action="/clearBasket" method="post">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 col-md-10 col-md-offset-1">
                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th>Quantity</th>
                                        <th class="text-center">Price HT</th>
                                        <th class="text-center">Price TTC</th>
                                        <th class="text-center">Total</th>
                                        <th>                <button type="submit" class="btn btn-danger">Suprimer</button> </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% if basket.quantities is defined %}
                                    {% for quantities in basket.quantities %}
                                        <tr>
                                            <td class="col-sm-8 col-md-6">

                                                <div class="media">

                                                    <a class="thumbnail pull-left" href="#"></a>
                                                    <div class="media-body">
                                                        <h4 class="media-heading"><a href="/fiche_prod/{{ quantities.product.id_product }}">{{ quantities.product.name }}</a></h4>
                                                        <span>Status: </span><span class="text-success"><strong>In Stock</strong></span>
                                                    </div>
                                                </div></td>
                                            <td class="col-sm-1 col-md-1" style="text-align: center">
                                                {{ quantities.quant }}
                                            </td>
                                            <td class="col-sm-1 col-md-1 text-center"><strong>{{ quantities.product.priceHT }}€</strong></td>
                                            <td class="col-sm-1 col-md-1 text-center"><strong>{{ quantities.product.priceTTC}}€</strong></td>
                                            <td class="col-sm-1 col-md-1 text-center"><strong>{{ quantities.product.priceTTC * quantities.quant }}€</strong></td>
                                            <td class="col-sm-1 col-md-1">
                                                <input type="checkbox" name="{{  quantities.product.idProduct }}" id="{{ 'product-' + quantities.product.idProduct }}" value="{{ quantities.product.idProduct }}" style="position: sticky;opacity: 1;">
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    {% endif %}

                                    <tr>
                                        <td>   </td>
                                        <td>   </td>
                                        <td>   </td>
                                        <td>   </td>
                                        <td><h5>Subtotal</h5></td>
                                        <td class="text-right"><h5><strong>{{ basket.totalTTC }} €</strong></h5></td>
                                    </tr>
                                    <tr>
                                        <td>   </td>
                                        <td>   </td>
                                        <td>   </td>
                                        <td>   </td>
                                        <td><h5>Estimated shipping</h5></td>
                                        <td class="text-right"><h5><strong>0€</strong></h5></td>
                                    </tr>
                                    <tr>
                                        <td>   </td>
                                        <td>   </td>
                                        <td>   </td>
                                        <td>   </td>
                                        <td><h3>Total</h3></td>
                                        <td class="text-right"><h3><strong>{{ basket.totalTTC }} €</strong></h3></td>
                                    </tr>
                                    <tr>
                                        <td>   </td>
                                        <td>   </td>
                                        <td>   </td>
                                        <td>   </td>
                                        <td>
                                            <a href="/">
                                                <span class="glyphicon glyphicon-shopping-cart"></span> Continue Shopping
                                            </a>
                                        </td>
                                        <td>
                                            <a href="/endBasket" class="btn btn-success">
                                                Checkout <span class="glyphicon glyphicon-play"></span>
                                            </a>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
            </form>
        {% endif %}
    {% endfor %}

{% endblock %}